repo: https://github.com/openwrt/openwrt.git
branch: v21.02.0-rc2
git_clone_dir: openwrt-21.02/openwrt-21.02.0-rc2
openwrt_root_dir: openwrt-21.02/openwrt-21.02.0-rc2
revision: 3e09cc496912264df05487ef0fae656c75a18a41

patch_folders:
  - patches-21.x/
